StartLog(LogFile="results/test-If-int-CompareAsStrings.gp.log")
# Test evaluating Integer conditions in various combinations
# - use CompareAsStrings so that comparison will be by using strings
SetProperty(PropertyName="IntegerProperty1",PropertyType="int",PropertyValue="1")
SetProperty(PropertyName="IntegerProperty0",PropertyType="int",PropertyValue="0")
# <
If(Name="Check_Integer_0_LT_Property1",Condition="0 < ${IntegerProperty1}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LT_Property1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is < ${IntegerProperty1}")
EndIf(Name="Check_Integer_0_LT_Property1")
If(Name="Check_Integer_0_LT_Property0",Condition="0 < ${IntegerProperty0}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LT_Property0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is < ${IntegerProperty0}")
EndIf(Name="Check_Integer_0_LT_Property0")
If(Name="Check_Integer_0_LT_1",Condition="0 < 1",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LT_1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is < 1")
EndIf(Name="Check_Integer_0_LT_1")
If(Name="Check_Integer_0_LT_0",Condition="0 < 0",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LT_0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is < 0")
EndIf(Name="Check_Integer_0_LT_0")
# <=
If(Name="Check_Integer_0_LE_Property1",Condition="0 <= ${IntegerProperty1}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LE_Property1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is <= ${IntegerProperty1}")
EndIf(Name="Check_Integer_0_LE_Property1")
If(Name="Check_Integer_0_LE_Property0",Condition="0 <= ${IntegerProperty0}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LE_Property0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is <= ${IntegerProperty0}")
EndIf(Name="Check_Integer_0_LE_Property0")
If(Name="Check_Integer_0_LE_1",Condition="0 <= 1",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LE_1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is <= 1")
EndIf(Name="Check_Integer_0_LE_1")
If(Name="Check_Integer_0_LE_0",Condition="0 <= 0",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_0_LE_0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="0 is <= 0")
EndIf(Name="Check_Integer_0_LE_0")
# >
If(Name="Check_Integer_1_GT_Property0",Condition="1 > ${IntegerProperty0}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GT_Property0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is > ${IntegerProperty0}")
EndIf(Name="Check_Integer_1_GT_Property0")
If(Name="Check_Integer_1_GT_Property1",Condition="1 > ${IntegerProperty1}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GT_Property1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is > ${IntegerProperty1}")
EndIf(Name="Check_Integer_1_GT_Property1")
If(Name="Check_Integer_1_GT_0",Condition="1 > 0",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GT_0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is > 0")
EndIf(Name="Check_Integer_1_GT_0")
If(Name="Check_Integer_1_GT_1",Condition="1 > 1",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GT_1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is > 1")
EndIf(Name="Check_Integer_1_GT_1")
# >=
If(Name="Check_Integer_1_GE_Property0",Condition="1 >= ${IntegerProperty0}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GE_Property0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is >= ${IntegerProperty0}")
EndIf(Name="Check_Integer_1_GE_Property0")
If(Name="Check_Integer_1_GE_Property1",Condition="1 >= ${IntegerProperty1}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GE_Property1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is >= ${IntegerProperty1}")
EndIf(Name="Check_Integer_1_GE_Property1")
If(Name="Check_Integer_1_GE_0",Condition="1 >= 0",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GE_0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is >= 0")
EndIf(Name="Check_Integer_1_GE_0")
If(Name="Check_Integer_1_GE_1",Condition="1 >= 1",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_GE_1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is >= True")
EndIf(Name="Check_Integer_1_GE_1")
# ==
If(Name="Check_Integer_1_EQ_Property1",Condition="1 == ${IntegerProperty1}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_EQ_Property1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is == ${IntegerProperty1}")
EndIf(Name="Check_Integer_1_EQ_Property1")
If(Name="Check_Integer_1_EQ_Property0",Condition="1 == ${IntegerProperty0}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_EQ_Property0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 == ${IntegerProperty0}")
EndIf(Name="Check_Integer_1_EQ_Property0")
If(Name="Check_Integer_1_EQ_1",Condition="1 == 1",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_EQ_1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is == 1")
EndIf(Name="Check_Integer_1_EQ_1")
If(Name="Check_Integer_1_EQ_0",Condition="1 == 0",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_EQ_0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 == 0")
EndIf(Name="Check_Integer_1_EQ_0")
# !=
If(Name="Check_Integer_1_NE_Property1",Condition="1 != ${IntegerProperty1}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_NE_Property1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is != ${IntegerProperty1}")
EndIf(Name="Check_Integer_1_NE_Property1")
If(Name="Check_Integer_1_NE_Property0",Condition="1 != ${IntegerProperty0}",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_NE_Property0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 != ${IntegerProperty0}")
EndIf(Name="Check_Integer_1_NE_Property0")
If(Name="Check_Integer_1_NE_1",Condition="1 != 1",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_NE_1_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 is != 1")
EndIf(Name="Check_Integer_1_NE_1")
If(Name="Check_Integer_1_NE_0",Condition="1 != 0",CompareAsStrings="True")
  SetProperty(PropertyName="Integer_1_NE_0_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="1 != 0")
EndIf(Name="Check_Integer_1_NE_0")
# Uncomment the next command to regenerate expected results
WritePropertiesToFile(OutputFile="expected-results/test-If-int-CompareAsStrings-out.txt",IncludeProperties="Integer_*_Test",SortOrder="Ascending")
WritePropertiesToFile(OutputFile="results/test-If-int-CompareAsStrings-out.txt",IncludeProperties="Integer_*_Test",SortOrder="Ascending")
CompareFiles(InputFile1="expected-results/test-If-int-CompareAsStrings-out.txt",InputFile2="results/test-If-int-CompareAsStrings-out.txt",IfDifferent="Warn")
