StartLog(LogFile="Results/test-If-bool.gp.log")
# Test evaluating boolean conditions in various combinations
SetProperty(PropertyName="BooleanPropertyTrue",PropertyType="bool",PropertyValue="True")
SetProperty(PropertyName="BooleanPropertyFalse",PropertyType="bool",PropertyValue="False")
# <
If(Name="Check_Boolean_False_LT_PropertyTrue",Condition="False < ${BooleanPropertyTrue}")
  SetProperty(PropertyName="Boolean_False_LT_PropertyTrue_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is < ${BooleanPropertyTrue}")
EndIf(Name="Check_Boolean_False_LT_PropertyTrue")
If(Name="Check_Boolean_False_LT_PropertyFalse",Condition="False < ${BooleanPropertyFalse}")
  SetProperty(PropertyName="Boolean_False_LT_PropertyFalse_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is < ${BooleanPropertyFalse}")
EndIf(Name="Check_Boolean_False_LT_PropertyFalse")
If(Name="Check_Boolean_False_LT_True",Condition="False < True")
  SetProperty(PropertyName="Boolean_False_LT_True_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is < True")
EndIf(Name="Check_Boolean_False_LT_True")
If(Name="Check_Boolean_False_LT_False",Condition="False < False")
  SetProperty(PropertyName="Boolean_False_LT_False_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is < False")
EndIf(Name="Check_Boolean_False_LT_False")
# <=
If(Name="Check_Boolean_False_LE_PropertyTrue",Condition="False <= ${BooleanPropertyTrue}")
  SetProperty(PropertyName="Boolean_False_LE_PropertyTrue_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is <= ${BooleanPropertyTrue}")
EndIf(Name="Check_Boolean_False_LE_PropertyTrue")
If(Name="Check_Boolean_False_LE_PropertyFalse",Condition="False <= ${BooleanPropertyFalse}")
  SetProperty(PropertyName="Boolean_False_LE_PropertyFalse_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is <= ${BooleanPropertyFalse}")
EndIf(Name="Check_Boolean_False_LE_PropertyFalse")
If(Name="Check_Boolean_False_LE_True",Condition="False <= True")
  SetProperty(PropertyName="Boolean_False_LE_True_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is <= True")
EndIf(Name="Check_Boolean_False_LE_True")
If(Name="Check_Boolean_False_LE_False",Condition="False <= False")
  SetProperty(PropertyName="Boolean_False_LE_False_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="False is <= False")
EndIf(Name="Check_Boolean_False_LE_False")
# >
If(Name="Check_Boolean_True_GT_PropertyFalse",Condition="True > ${BooleanPropertyFalse}")
  SetProperty(PropertyName="Boolean_True_GT_PropertyFalse_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is > ${BooleanPropertyFalse}")
EndIf(Name="Check_Boolean_True_GT_PropertyFalse")
If(Name="Check_Boolean_True_GT_PropertyTrue",Condition="True > ${BooleanPropertyTrue}")
  SetProperty(PropertyName="Boolean_True_GT_PropertyTrue_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is > ${BooleanPropertyTrue}")
EndIf(Name="Check_Boolean_True_GT_PropertyTrue")
If(Name="Check_Boolean_True_GT_False",Condition="True > False")
  SetProperty(PropertyName="Boolean_True_GT_False_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is > False")
EndIf(Name="Check_Boolean_True_GT_False")
If(Name="Check_Boolean_True_GT_True",Condition="True > True")
  SetProperty(PropertyName="Boolean_True_GT_True_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is > True")
EndIf(Name="Check_Boolean_True_GT_True")
# >=
If(Name="Check_Boolean_True_GE_PropertyFalse",Condition="True >= ${BooleanPropertyFalse}")
  SetProperty(PropertyName="Boolean_True_GE_PropertyFalse_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is >= ${BooleanPropertyFalse}")
EndIf(Name="Check_Boolean_True_GE_PropertyFalse")
If(Name="Check_Boolean_True_GE_PropertyTrue",Condition="True >= ${BooleanPropertyTrue}")
  SetProperty(PropertyName="Boolean_True_GE_PropertyTrue_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is >= ${BooleanPropertyTrue}")
EndIf(Name="Check_Boolean_True_GE_PropertyTrue")
If(Name="Check_Boolean_True_GE_False",Condition="True >= False")
  SetProperty(PropertyName="Boolean_True_GE_False_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is >= False")
EndIf(Name="Check_Boolean_True_GE_False")
If(Name="Check_Boolean_True_GE_True",Condition="True >= True")
  SetProperty(PropertyName="Boolean_True_GE_True_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is >= True")
EndIf(Name="Check_Boolean_True_GE_True")
# ==
If(Name="Check_Boolean_True_EQ_PropertyTrue",Condition="True == ${BooleanPropertyTrue}")
  SetProperty(PropertyName="Boolean_True_EQ_PropertyTrue_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is == ${BooleanPropertyTrue}")
EndIf(Name="Check_Boolean_True_EQ_PropertyTrue")
If(Name="Check_Boolean_True_EQ_PropertyFalse",Condition="True == ${BooleanPropertyFalse}")
  SetProperty(PropertyName="Boolean_True_EQ_PropertyFalse_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True == ${BooleanPropertyFalse}")
EndIf(Name="Check_Boolean_True_EQ_PropertyFalse")
If(Name="Check_Boolean_True_EQ_True",Condition="True == True")
  SetProperty(PropertyName="Boolean_True_EQ_True_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is == True")
EndIf(Name="Check_Boolean_True_EQ_True")
If(Name="Check_Boolean_True_EQ_False",Condition="True == False")
  SetProperty(PropertyName="Boolean_True_EQ_False_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True == False")
EndIf(Name="Check_Boolean_True_EQ_False")
# !=
If(Name="Check_Boolean_True_NE_PropertyTrue",Condition="True != ${BooleanPropertyTrue}")
  SetProperty(PropertyName="Boolean_True_NE_PropertyTrue_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is != ${BooleanPropertyTrue}")
EndIf(Name="Check_Boolean_True_NE_PropertyTrue")
If(Name="Check_Boolean_True_NE_PropertyFalse",Condition="True != ${BooleanPropertyFalse}")
  SetProperty(PropertyName="Boolean_True_NE_PropertyFalse_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True != ${BooleanPropertyFalse}")
EndIf(Name="Check_Boolean_True_NE_PropertyFalse")
If(Name="Check_Boolean_True_NE_True",Condition="True != True")
  SetProperty(PropertyName="Boolean_True_NE_True_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True is != True")
EndIf(Name="Check_Boolean_True_NE_True")
If(Name="Check_Boolean_True_NE_False",Condition="True != False")
  SetProperty(PropertyName="Boolean_True_NE_False_Test",PropertyType="bool",PropertyValue="True")
  Message(Message="True != False")
EndIf(Name="Check_Boolean_True_NE_False")
# Uncomment the next command to regenerate expected results
#WritePropertiesToFile(OutputFile="expected-results/test-If-bool-out.txt",FileFormat="NameValue",IncludeProperties="Boolean_*_Test",SortOrder="Ascending")
WritePropertiesToFile(OutputFile="results/test-If-bool-out.txt",FileFormat="NameValue",IncludeProperties="Boolean_*_Test",SortOrder="Ascending")
CompareFiles(InputFile1="expected-results/test-If-bool-out.txt",InputFile2="results/test-If-bool-out.txt",IfDifferent="Warn")
